# Generated by Django 5.0.4 on 2024-04-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile",
            field=models.ImageField(default=1, upload_to="media"),
            preserve_default=False,
        ),
    ]
