# Generated by Django 5.0.4 on 2024-05-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="default/profile2.png",
                null=True,
                upload_to="Customer_Profile",
            ),
        ),
    ]
