# Generated by Django 5.0.4 on 2024-05-03 14:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="IN"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="default/profile2.png",
                null=True,
                upload_to="Customer_Profile",
            ),
        ),
    ]
