# Generated by Django 5.0.4 on 2024-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customer_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="Customer_Profile"
            ),
        ),
    ]
