# Generated by Django 5.0.4 on 2024-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customer_phone_alter_customer_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="default/profile2.png",
                null=True,
                upload_to="Customer_Profile",
            ),
        ),
    ]
