# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-05-05 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Computer Name",
                    ),
                ),
                (
                    "processor",
                    models.CharField(
                        choices=[
                            ("INTEL_I5", "Intel Core i5"),
                            ("INTEL_I7", "Intel Core i7"),
                            ("INTEL_I9", "Intel Core i9"),
                            ("RYZEN_9", "AMD Ryzen 9"),
                            ("RYZEN_7", "AMD Ryzen 7"),
                            ("RYZEN_5", "AMD Ryzen 5"),
                            ("APPLE_M1", "Apple M1"),
                            ("SD", "Qualcomm Snapdragon"),
                            ("EXYNOX", "Samsung Exynos"),
                            ("DIMENSITY", "MediaTek Dimensity"),
                        ],
                        default=("INTEL_I5", "Intel Core i5"),
                        max_length=100,
                        verbose_name="Processor",
                    ),
                ),
                (
                    "ram",
                    models.IntegerField(
                        choices=[
                            (2, "2 GB"),
                            (4, "4 GB"),
                            (8, "8 GB"),
                            (16, "16 GB"),
                            (32, "32 GB"),
                            (64, "64 GB"),
                            (128, "128 GB"),
                            (256, "256 GB"),
                        ],
                        default=(2, "2 GB"),
                        verbose_name="Random Access Memory",
                    ),
                ),
                (
                    "gpu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NVIDIA_GEFORCE_RTX_3090", "NVIDIA GeForce RTX 3090"),
                            ("NVIDIA_GEFORCE_RTX_3080", "NVIDIA GeForce RTX 3080"),
                            ("NVIDIA_GEFORCE_RTX_3070", "NVIDIA GeForce RTX 3070"),
                            ("NVIDIA_GEFORCE_RTX_3060", "NVIDIA GeForce RTX 3060"),
                            ("AMD_RADEONRX_6900", "AMD Radeon RX 6900 XT"),
                            ("AMD_RADEONRX_6800", "AMD Radeon RX 6800 XT"),
                            ("AMD_RADEONRX_6700", "AMD Radeon RX 6700 XT"),
                        ],
                        default=("NVIDIA_GEFORCE_RTX_3090", "NVIDIA GeForce RTX 3090"),
                        max_length=100,
                        null=True,
                        verbose_name="Graphics Card",
                    ),
                ),
                ("wifi", models.BooleanField(default=True, verbose_name="WiFi")),
                ("usage_price", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Computer Details",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payer_username",
                    models.CharField(max_length=100, verbose_name="Payer Name"),
                ),
                ("transaction_id", models.CharField(verbose_name="Transaction Id")),
                (
                    "transaction_amount",
                    models.FloatField(verbose_name="Transaction Amount"),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="cafehome.computer",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transactions Detail",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
