# Generated by Django 5.0.4 on 2024-04-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Computer Name",
                    ),
                ),
                (
                    "processor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Intel Core i9", "Intel Core i9"),
                            ("Intel Core i7", "Intel Core i7"),
                            ("Intel Core i5", "Intel Core i5"),
                            ("AMD Ryzen 9", "AMD Ryzen 9"),
                            ("AMD Ryzen 7", "AMD Ryzen 7"),
                            ("AMD Ryzen 5", "AMD Ryzen 5"),
                            ("Apple M1", "Apple M1"),
                            ("Qualcomm Snapdragon", "Qualcomm Snapdragon"),
                            ("Samsung Exynos", "Samsung Exynos"),
                            ("MediaTek Dimensity", "MediaTek Dimensity"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Processor",
                    ),
                ),
                (
                    "ram",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (2, "2 GB"),
                            (4, "4 GB"),
                            (8, "8 GB"),
                            (16, "16 GB"),
                            (32, "32 GB"),
                            (64, "64 GB"),
                            (128, "128 GB"),
                            (256, "256 GB"),
                        ],
                        null=True,
                        verbose_name="Random Access Memory",
                    ),
                ),
                (
                    "gpu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NVIDIA GeForce RTX 3090", "NVIDIA GeForce RTX 3090"),
                            ("NVIDIA GeForce RTX 3080", "NVIDIA GeForce RTX 3080"),
                            ("NVIDIA GeForce RTX 3070", "NVIDIA GeForce RTX 3070"),
                            ("NVIDIA GeForce RTX 3060", "NVIDIA GeForce RTX 3060"),
                            ("AMD Radeon RX 6900 XT", "AMD Radeon RX 6900 XT"),
                            ("AMD Radeon RX 6800 XT", "AMD Radeon RX 6800 XT"),
                            ("AMD Radeon RX 6700 XT", "AMD Radeon RX 6700 XT"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Graphics Card",
                    ),
                ),
                ("wifi", models.BooleanField(default=True, verbose_name="WiFi")),
                ("usage_price", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Computer Detail",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Customer Name"),
                ),
                ("transaction_id", models.CharField(verbose_name="Transaction Id")),
                (
                    "transaction_date",
                    models.DateTimeField(verbose_name="Transaction Date"),
                ),
                (
                    "transaction_amount",
                    models.FloatField(verbose_name="Transaction Amount"),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cafehome.computer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transactions Detail",
                "ordering": ["transaction_id"],
            },
        ),
    ]
