# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-05-06 07:47

import django.db.models.deletion
from django.conf import settings
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Computer Name",
                    ),
                ),
                (
                    "processor",
                    models.CharField(
                        choices=[
                            ("Intel Core i5", "Intel Core i5"),
                            ("Intel Core i7", "Intel Core i7"),
                            ("Intel Core i9", "Intel Core i9"),
                            ("AMD Radeon RX 6700 XT", "AMD Radeon RX 6700 XT"),
                            ("AMD Radeon RX 6800 XT", "AMD Radeon RX 6800 XT"),
                            ("AMD Radeon RX 6900 XT", "AMD Radeon RX 6900 XT"),
                            ("Apple M1", "Apple M1"),
                            ("Samsung Exynos", "Samsung Exynos"),
                            ("MediaTek Dimensity", "MediaTek Dimensity"),
                        ],
                        default="Intel Core i5",
                        max_length=100,
                        verbose_name="Processor",
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        choices=[
                            ("2 GB", "2 GB"),
                            ("4 GB", "4 GB"),
                            ("8 GB", "8 GB"),
                            ("16 GB", "16 GB"),
                            ("64 GB", "64 GB"),
                        ],
                        default="2 GB",
                        max_length=10,
                        verbose_name="Random Access Memory",
                    ),
                ),
                (
                    "gpu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NVIDIA GeForce RTX 3060", "NVIDIA GeForce RTX 3060"),
                            ("NVIDIA GeForce RTX 3070", "NVIDIA GeForce RTX 3070"),
                            ("NVIDIA GeForce RTX 3080", "NVIDIA GeForce RTX 3080"),
                            ("NVIDIA GeForce RTX 3090", "NVIDIA GeForce RTX 3090"),
                            ("AMD Radeon RX 6800 XT", "AMD Radeon RX 6800 XT"),
                            ("AMD Radeon RX 6700 XT", "AMD Radeon RX 6700 XT"),
                            ("AMD Radeon RX 6900 XT", "AMD Radeon RX 6900 XT"),
                        ],
                        default="NVIDIA GeForce RTX 3060",
                        max_length=100,
                        null=True,
                        verbose_name="Graphics Card",
                    ),
                ),
                ("wifi", models.BooleanField(default=True, verbose_name="WiFi")),
                ("usage_price", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Computer Details",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "payer_username",
                    models.CharField(max_length=100, verbose_name="Payer Name"),
                ),
                ("transaction_id", models.CharField(verbose_name="Transaction Id")),
                (
                    "transaction_amount",
                    models.FloatField(verbose_name="Transaction Amount"),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="cafehome.computer",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transactions Detail",
                "ordering": ["-created"],
            },
        ),
    ]
