# Generated by Django 5.0.4 on 2024-04-26 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=30)),
                ("transaction_id", models.IntegerField()),
                ("transaction_date", models.DateField()),
                ("transaction_amount", models.IntegerField()),
                (
                    "computer_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cafehome.computer",
                    ),
                ),
                (
                    "customer_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
