# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="computer_details",
            new_name="computer",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="customer_details",
            new_name="customer",
        ),
        migrations.AlterField(
            model_name="computer",
            name="processor",
            field=models.CharField(
                choices=[
                    ("INTEL_I5", "Intel Core i5"),
                    ("INTEL_I7", "Intel Core i7"),
                    ("INTEL_I9", "Intel Core i9"),
                    ("RYZEN_9", "AMD Ryzen 9"),
                    ("RYZEN_7", "AMD Ryzen 7"),
                    ("RYZEN_5", "AMD Ryzen 5"),
                    ("APPLE_M1", "Apple M1"),
                    ("SD", "Qualcomm Snapdragon"),
                    ("EXYNOX", "Samsung Exynos"),
                    ("DIMENSITY", "MediaTek Dimensity"),
                ],
                default="INTEL_I5",
                max_length=100,
                verbose_name="Processor",
            ),
        ),
    ]
