# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0002_rename_computer_details_transaction_computer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="gpu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NVIDIA_DEFORCE_RTX_3090", "NVIDIA GeForce RTX 3090"),
                    ("NVIDIA_DEFORCE_RTX_3080", "NVIDIA GeForce RTX 3080"),
                    ("NVIDIA_DEFORCE_RTX_3070", "NVIDIA GeForce RTX 3070"),
                    ("NVIDIA_DEFORCE_RTX_3060", "NVIDIA GeForce RTX 3060"),
                    ("AMD_RADEONRX_6900", "AMD Radeon RX 6900 XT"),
                    ("AMD_RADEONRX_6800", "AMD Radeon RX 6800 XT"),
                    ("AMD_RADEONRX_6700", "AMD Radeon RX 6700 XT"),
                ],
                default="NVIDIA_DEFORCE_RTX_3090",
                max_length=100,
                null=True,
                verbose_name="Graphics Card",
            ),
        ),
    ]
