# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="usage_price",
            field=models.IntegerField(default=10),
        ),
    ]
