# Generated by Django 5.0.4 on 2024-05-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="customer_name",
            new_name="payer_username",
        ),
        migrations.AlterField(
            model_name="computer",
            name="processor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Intel Core i9", "Intel Core i9"),
                    ("Intel Core i7", "Intel Core i7"),
                    ("Intel Core i5", "Intel Core i5"),
                    ("AMD Ryzen 9", "AMD Ryzen 9"),
                    ("AMD Ryzen 7", "AMD Ryzen 7"),
                    ("AMD Ryzen 5", "AMD Ryzen 5"),
                    ("Apple M1", "Apple M1"),
                    ("Qualcomm Snapdragon", "Qualcomm Snapdragon"),
                    ("Samsung Exynos", "Samsung Exynos"),
                    ("MediaTek Dimensity", "MediaTek Dimensity"),
                ],
                default="Intel Core i5",
                max_length=100,
                null=True,
                verbose_name="Processor",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="ram",
            field=models.IntegerField(
                choices=[
                    (2, "2 GB"),
                    (4, "4 GB"),
                    (8, "8 GB"),
                    (16, "16 GB"),
                    (32, "32 GB"),
                    (64, "64 GB"),
                    (128, "128 GB"),
                    (256, "256 GB"),
                ],
                default=2,
                verbose_name="Random Access Memory",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="usage_price",
            field=models.IntegerField(default=0),
        ),
    ]
