# Generated by Django 5.0.4 on 2024-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0002_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="computer",
            options={"ordering": ["name"], "verbose_name": "Computer Detail"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["transaction_id"],
                "verbose_name": "Transactions Detail",
            },
        ),
        migrations.AddField(
            model_name="computer",
            name="usage_price",
            field=models.IntegerField(default=1, verbose_name="Usage Price"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="computer",
            name="gpu",
            field=models.CharField(max_length=30, verbose_name="Graphics Card"),
        ),
        migrations.AlterField(
            model_name="computer",
            name="name",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Computer Name"
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="processor",
            field=models.CharField(max_length=30, verbose_name="Processor"),
        ),
        migrations.AlterField(
            model_name="computer",
            name="ram",
            field=models.IntegerField(verbose_name="Random Access Memory"),
        ),
        migrations.AlterField(
            model_name="computer",
            name="wifi",
            field=models.BooleanField(default=True, verbose_name="WiFi"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="customer_name",
            field=models.CharField(max_length=30, verbose_name="Customer Name"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_amount",
            field=models.IntegerField(verbose_name="Transaction Amount"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(verbose_name="Transaction Date"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.IntegerField(verbose_name="Transaction Id"),
        ),
    ]
