# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-05-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0002_alter_computer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_status",
            field=models.CharField(
                default=1, max_length=10, verbose_name="Transaction Status"
            ),
            preserve_default=False,
        ),
    ]
