# Generated by Django 5.0.4 on 2024-04-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0003_alter_computer_options_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="gpu",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Graphics Card"
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="processor",
            field=models.CharField(max_length=30, null=True, verbose_name="Processor"),
        ),
        migrations.AlterField(
            model_name="computer",
            name="ram",
            field=models.IntegerField(null=True, verbose_name="Random Access Memory"),
        ),
        migrations.AlterField(
            model_name="computer",
            name="usage_price",
            field=models.IntegerField(null=True, verbose_name="Usage Price"),
        ),
        migrations.AlterField(
            model_name="computer",
            name="wifi",
            field=models.BooleanField(default=True, null=True, verbose_name="WiFi"),
        ),
    ]
