# Generated by Django 5.0.4 on 2024-05-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0003_rename_customer_name_transaction_payer_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="computer",
            new_name="computer_details",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="customer",
            new_name="customer_details",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payer_username",
            field=models.CharField(max_length=100, verbose_name="Payer Name"),
        ),
    ]
