# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-05-04 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0003_alter_computer_gpu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="computer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computers",
                to="cafehome.computer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
