# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0004_alter_transaction_computer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="gpu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NVIDIA_GEFORCE_RTX_3090", "NVIDIA GeForce RTX 3090"),
                    ("NVIDIA_GEFORCE_RTX_3080", "NVIDIA GeForce RTX 3080"),
                    ("NVIDIA_GEFORCE_RTX_3070", "NVIDIA GeForce RTX 3070"),
                    ("NVIDIA_GEFORCE_RTX_3060", "NVIDIA GeForce RTX 3060"),
                    ("AMD_RADEONRX_6900", "AMD Radeon RX 6900 XT"),
                    ("AMD_RADEONRX_6800", "AMD Radeon RX 6800 XT"),
                    ("AMD_RADEONRX_6700", "AMD Radeon RX 6700 XT"),
                ],
                default=("NVIDIA_GEFORCE_RTX_3090", "NVIDIA GeForce RTX 3090"),
                max_length=100,
                null=True,
                verbose_name="Graphics Card",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="processor",
            field=models.CharField(
                choices=[
                    ("INTEL_I5", "Intel Core i5"),
                    ("INTEL_I7", "Intel Core i7"),
                    ("INTEL_I9", "Intel Core i9"),
                    ("RYZEN_9", "AMD Ryzen 9"),
                    ("RYZEN_7", "AMD Ryzen 7"),
                    ("RYZEN_5", "AMD Ryzen 5"),
                    ("APPLE_M1", "Apple M1"),
                    ("SD", "Qualcomm Snapdragon"),
                    ("EXYNOX", "Samsung Exynos"),
                    ("DIMENSITY", "MediaTek Dimensity"),
                ],
                default=("INTEL_I5", "Intel Core i5"),
                max_length=100,
                verbose_name="Processor",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="ram",
            field=models.IntegerField(
                choices=[
                    (2, "2 GB"),
                    (4, "4 GB"),
                    (8, "8 GB"),
                    (16, "16 GB"),
                    (32, "32 GB"),
                    (64, "64 GB"),
                    (128, "128 GB"),
                    (256, "256 GB"),
                ],
                default=(2, "2 GB"),
                verbose_name="Random Access Memory",
            ),
        ),
    ]
