# Generated by Django 5.0.4 on 2024-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0004_alter_computer_gpu_alter_computer_processor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="gpu",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Graphics Card"
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Computer Name",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="processor",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Processor"
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="ram",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Random Access Memory"
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="usage_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="wifi",
            field=models.BooleanField(default=True, verbose_name="WiFi"),
        ),
    ]
