# Generated by Django 5.0.4 on 2024-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0005_alter_transaction_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="gpu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NVIDIA_DEFORCE_RTX_3090", "NVIDIA GeForce RTX 3090"),
                    ("NVIDIA_DEFORCE_RTX_3080", "NVIDIA GeForce RTX 3080"),
                    ("NVIDIA_DEFORCE_RTX_3070", "NVIDIA GeForce RTX 3070"),
                    ("NVIDIA_DEFORCE_RTX_3060", "NVIDIA GeForce RTX 3060"),
                    ("AMD_RADEONRX_6900", "AMD Radeon RX 6900 XT"),
                    ("AMD_RADEONRX_6800", "AMD Radeon RX 6800 XT"),
                    ("AMD_RADEONRX_6700", "AMD Radeon RX 6700 XT"),
                ],
                max_length=100,
                null=True,
                verbose_name="Graphics Card",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="processor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INTEL_I9", "Intel Core i9"),
                    ("INTEOL_I7", "Intel Core i7"),
                    ("INTEOL_I5", "Intel Core i5"),
                    ("RYZEN_9", "AMD Ryzen 9"),
                    ("RYZEN_7", "AMD Ryzen 7"),
                    ("RYZEN_5", "AMD Ryzen 5"),
                    ("APPLE_M1", "Apple M1"),
                    ("SD", "Qualcomm Snapdragon"),
                    ("EXYNOX", "Samsung Exynos"),
                    ("DIMENSITY", "MediaTek Dimensity"),
                ],
                default="Intel Core i5",
                max_length=100,
                null=True,
                verbose_name="Processor",
            ),
        ),
    ]
