# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-05-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0005_alter_computer_gpu_alter_computer_processor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="computer",
            options={"ordering": ["name"], "verbose_name": "Computer Details"},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="computer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="cafehome.computer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
