# Generated by Django 5.0.4 on 2024-04-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0005_alter_computer_gpu_alter_computer_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="computer_id",
            new_name="computer",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="customer_id",
            new_name="customer",
        ),
    ]
