# Generated by Django 5.0.4 on 2024-05-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafehome", "0006_alter_computer_gpu_alter_computer_processor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="processor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INTEL_I9", "Intel Core i9"),
                    ("INTEL_I7", "Intel Core i7"),
                    ("INTEL_I5", "Intel Core i5"),
                    ("RYZEN_9", "AMD Ryzen 9"),
                    ("RYZEN_7", "AMD Ryzen 7"),
                    ("RYZEN_5", "AMD Ryzen 5"),
                    ("APPLE_M1", "Apple M1"),
                    ("SD", "Qualcomm Snapdragon"),
                    ("EXYNOX", "Samsung Exynos"),
                    ("DIMENSITY", "MediaTek Dimensity"),
                ],
                default="INTEL_I5",
                max_length=100,
                null=True,
                verbose_name="Processor",
            ),
        ),
    ]
